import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import SessionProvider from "./components/SessionProvider";
import { getServerSession } from "next-auth";
import "@uploadthing/react/styles.css";

const NotoSans = Noto_Sans_Thai({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Silapakorn",
  description: "Generated by create next app",
};

export default  async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body className={NotoSans.className}>
        <Toaster/>
        
        <SessionProvider session={session}>
          {children}
        </SessionProvider>
        </body>
    </html>
  );
}
